# Generated by Django 6.0.8 on 2026-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='current',
            new_name='is_current',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='available_for_work',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='current',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_url',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Séparer les technologies par des virgules.', max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de données'), ('tools', 'Outils'), ('other', 'Autre')], max_length=30),
        ),
    ]
