services:
  docs:
    image: nancy_portfolio_local_docs
    container_name: nancy_portfolio_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - path: ./.envs/.local/.django
        required: false
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./nancy_portfolio:/app/nancy_portfolio:z
    ports:
      - '9000:9000'
    command: /start-docs
